### ISSUE TITLE
consume sshuttle.conf

### ISSUE THREAD

**Issue by drewwells** [flashashen/no-YOU-talk-to-the-hand#4]
Love the project and the name.

I built a poor man's version of this with sshuttle's config file. I found this while looking for a solution to sshuttle not detecting the ssh tunnel was dead. It would be terrific if this project supported sshuttle's config file. It would eliminate a lot of documentation/learning curve needed here.

**Comment by flashashen** [comment]
Thanks, but I’m not aware of a sshuttle config file. Can you privide a link?

**Comment by flashashen** [comment]
closing as no feedback provided
